#!/bin/sh

[ -x /etc/init.d/complaints-queue ] || exit 0

/etc/init.d/complaints-queue stop

sleep 1

[ -x /usr/sbin/update-rc.d ] || exit 0

/usr/sbin/update-rc.d -f complaints-queue remove

[ -d /srv/complaints.queue ] || exit 0

find /srv/complaints.queue -name \*.pyc -delete
rm -f /srv/complaints.queue/var/*.pid
